// Package store persists pending and decided approvals, and Wardryx's
// policy-as-code documents. Approvals are the durable half of Wardryx's
// stateless human-in-the-loop design (see internal/approval): a hold
// creates one row here; a later admin decision updates it in place. Nothing
// about a hold parks a connection or blocks a goroutine waiting for a
// human -- the caller polls or is notified out of band, and the eventual
// grant is proven by a signed token (internal/approval), not by this store
// being consulted again on the hot path. Policies are the durable half of
// the policy-as-code admin API (internal/api's admin policy routes):
// internal/pdp's Engine holds the compiled, in-memory policy.Set it decides
// against, and this store is what an admin write persists so the next
// process restart (or, for Postgres, a peer wardryx instance) can rebuild
// that Set rather than losing an API-managed policy on every restart the
// way file-based -policy never had to worry about.
//
// Two implementations satisfy Store: Memory (used when no Postgres DSN is
// configured) and Postgres (pgx/v5, embedded schema.sql, additive
// migrations). Both have identical observable behavior, so callers -- the
// HTTP API, the approvals CLI -- depend only on the interface.
package store

import (
	"context"
	"errors"
	"time"

	"github.com/TAIPANBOX/wardryx/internal/policy"
)

// Sentinel errors returned by Store implementations. Wrapped with
// additional context via fmt.Errorf's %w verb, so callers can branch with
// errors.Is.
var (
	// ErrNotFound means no approval (or, for the policy methods below, no
	// policy) exists with the given id.
	ErrNotFound = errors.New("store: approval not found")
	// ErrAlreadyDecided means DecideApproval was called on an approval that
	// already carries a decision. An approval may be decided exactly once.
	ErrAlreadyDecided = errors.New("store: approval already decided")
)

// Approval is one pending or decided human-in-the-loop approval, the Go
// shape of one row of the `approvals` table (schema.sql).
type Approval struct {
	// ApprovalID uniquely identifies this approval. Assigned by
	// internal/approval when the hold is created.
	ApprovalID string
	// AgentID is the agent:// URI the held DecideRequest named.
	AgentID string
	// RunID is the run the held DecideRequest named.
	RunID string
	// RequestedAt is when the hold was created.
	RequestedAt time.Time
	// DecidedAt is the zero time until an admin decides the approval.
	DecidedAt time.Time
	// DecidedBy is the admin-supplied identifier of who decided it; empty
	// until decided.
	DecidedBy string
	// Decision is "" while pending, then "grant" or "deny" once decided.
	Decision string
	// Context carries the rest of the held request (tool_names, model,
	// est_cost_usd, attestation_method, on_behalf_of, the org that owns
	// this approval, and the Reason/PolicyVersion the PDP computed) as
	// free-form data, stored as the `context_json` column. internal/api
	// uses Context["org"] to scope GET /v1/approvals per caller, and
	// internal/approval uses Context["tool_names"] to rebind a minted
	// token to the exact tool set that was held.
	Context map[string]any
}

// Pending reports whether the approval has not yet been decided.
func (a Approval) Pending() bool { return a.Decision == "" }

// PolicyRecord is one stored policy-as-code document: an operator-assigned
// id (distinct from Policy.Name, which need not be unique or URL-safe),
// the policy body itself, and when it was last written. Reusing
// policy.Policy's existing JSON-tagged struct as the stored value (rather
// than a separate schema) means a PolicyRecord round-trips through
// policy.Compile unchanged -- see internal/api's admin policy routes.
type PolicyRecord struct {
	// ID addresses this policy for Get/Put/Delete, e.g. in
	// PUT /v1/policies/{id}. Assigned by the caller (internal/api), not
	// generated by the store: a policy update is a replace-by-id, not an
	// append.
	ID string
	// Policy is the stored document.
	Policy policy.Policy
	// UpdatedAt is when this id was last written by PutPolicy.
	UpdatedAt time.Time
}

// Store persists approvals and policy-as-code documents. Implementations
// must make DecideApproval atomic: a second decision on an already-decided
// approval must fail with ErrAlreadyDecided rather than silently
// overwriting the first one, since the first decision may already have
// minted a live approval_token.
type Store interface {
	// CreateApproval inserts a new pending approval. ApprovalID must be
	// unique; Decision, DecidedAt, and DecidedBy on a must be zero values.
	CreateApproval(ctx context.Context, a Approval) error

	// GetApproval returns the approval with the given id, or ErrNotFound.
	GetApproval(ctx context.Context, id string) (Approval, error)

	// ListApprovals returns every approval (pending and decided), ordered
	// by RequestedAt ascending. Callers that need to scope the list (e.g.
	// by org) filter the result themselves using Approval.Context.
	ListApprovals(ctx context.Context) ([]Approval, error)

	// DecideApproval records decision ("grant" or "deny") and decidedBy
	// against the approval with the given id, and returns the updated
	// approval. It returns ErrNotFound if no such approval exists, or
	// ErrAlreadyDecided if it was already decided.
	DecideApproval(ctx context.Context, id, decision, decidedBy string, decidedAt time.Time) (Approval, error)

	// TryRedeem atomically claims key if (and only if) it has not already
	// been claimed, and reports whether this call was the one that did so:
	// true the first time a given key is presented, false on every
	// subsequent call with that same key. It is the check-and-set primitive
	// WARDRYX_APPROVAL_SINGLE_USE is built on (internal/api, keyed by
	// approval.RedemptionKey), and implementations must make it race-safe
	// under concurrent callers -- exactly one concurrent caller for a given
	// key may ever observe true.
	TryRedeem(ctx context.Context, key string) (bool, error)

	// Close releases any resources held by the store (e.g. a Postgres
	// connection pool). Memory's Close is a no-op.
	Close() error

	// PutPolicy inserts a new policy, or replaces the existing one, under
	// id. Unlike CreateApproval, this is upsert semantics throughout: the
	// admin policy API's PUT /v1/policies/{id} is a replace-by-id, not a
	// create-only operation, so callers never need a separate "does this id
	// already exist" check before writing.
	PutPolicy(ctx context.Context, id string, p policy.Policy, updatedAt time.Time) error

	// GetPolicy returns the policy stored under id, or ErrNotFound.
	GetPolicy(ctx context.Context, id string) (PolicyRecord, error)

	// ListPolicies returns every stored policy, ordered by id, for
	// rebuilding a policy.Set (e.g. at startup, or after ANY write, via
	// policy.Compile) and for GET /v1/policies.
	ListPolicies(ctx context.Context) ([]PolicyRecord, error)

	// DeletePolicy removes the policy stored under id. Returns ErrNotFound
	// if no such policy exists.
	DeletePolicy(ctx context.Context, id string) error
}
